version: '3.1'

services:

  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef
      POSTGRES_USER: app
      POSTGRES_DB: app
    ports:
      - '5432:5432'
    volumes:
      - ./data1:/var/lib/postgresql/data